### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by kirill-tolmachev** [Finikov/DreamTeam#4]
Пожалуйста, добавьте в проект файл .gitignore во избежание копирования на репозиторий NuGet-зависимостей и скомпилированных файлов. После этого почистите репозиторий проекта в соответствии с .gitignore: https://stackoverflow.com/questions/19663093/

Пример .gitignore-файла для C#-проекта:
https://gist.github.com/kmorcinek/2710267

В случае необходимости восстановления NuGet-зависимостей при клонировании решения, используйте функцию NuGet Restore:
https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore

**Comment by TatyanaEfremova** [comment]
А можно поподробнее как почистить?

**Comment by TatyanaEfremova** [comment]
И что именно почистить?

**Comment by kirill-tolmachev** [comment]
Это работает так:

1. Когда у вас не был создан файл .gitignore вы загрузили на репозиторий много лишних вещей, которые в общем-то не обязательны. Например, это NuGet-библиотеки, которые можно скачать из менеджера пакетов при компиляции проекта или скомпилированные файлы приложения. Их обычно стараются не загружать, чтобы репозиторий был чище/легче.

2. Вы добавили файл .gitignore (он описывает, какие файлы/папки при коммите нужно игнорировать), и теперь гит понимает, что новые файлы такого типа загружать не нужно. Но гит не знает, что делать с файлами, которые уже были загружены (без вашего ведома он ничего с репозитория удалять не будет). Поэтому он не делает ничего.

3. Чтобы удалить файлы, попадающие под .gitignore, но которые были загружены в репозиторий до того, как он был создан, нужно произвести следующие шаги:
- Закоммитить все текущие изменения
- Выполнить команду `git rm -r --cached .`
- Выполнить команду `git add .`
- Закоммитить то, что получилось

Это чуть подробнее описывается по ссылке, которую я прикреплял выше:
https://stackoverflow.com/questions/19663093/

**Comment by Finikov** [comment]
А это можно выполнить с клиента SmartGit?

**Comment by kirill-tolmachev** [comment]
Я не знаю (возможно, нет), но все графические интерфейсы над Git - это обертки вокруг консольного приложения, так что я бы просто нашел место, откуда он запускается, и выполнил бы вручную.

Кстати, если вдруг SmartGit прописал вам путь к Git в PATH, то вы можете просто сделать всё из командной строки.
